number1=input('Enter Number 1')
number2=input('Enter Number 2')
number3=input('Enter Number 3')
print(number1,number2)
sum=int(number1)+int(number2)
print(sum)
Difference= int(number1) - int(number2)
Multiplication= int(number1) * int(number2)
Division= int(number1)/int (number2)
print(Difference)
print(Multiplication)
print(Division)
sum =int(number1)+int(number2)+int(number3)
Difference= int(number1)-int(number2)-int(number3)
Multiplication= int(number1)*int(number2)*int(number3)
Division= int(number1)/int(number2)/int(number3)
print(Difference)
print(Multiplication)
print(Division)
import math
#Return the value of 9 raised to the power of 3
print(math.pow(9, 3))
print(math.tan(9))
print(math.floor(9))
print(math.isqrt(9))
print(math.gcd(9,6))
print(math.isclose(9,3))
print(math.log(9,7))
print(math.pow(9,8))
print(math.trunc(8))
print(math.isinf(9))
